---
# tasks file for openstack      
# Install Chrony and Configure NTP server for time adjustment
# [1] Install Chrony
- name: "Install Chrony"
  yum:
    name: "chrony"
    state: "present"

#  #2. Cette tâche active le service Apache
#  - name: "apache service activation"
#    service:
#    name: "httpd"
#    state: "started"
#    enabled: yes
#
#    #3. Cette tâche fait appel à un autre fichier de configuration pour installer PHP. Elle est exécutée uniquement si la variable php_install est à vraie (par défaut, elle est à faux)
#    - name: "install php7 packages"
#      include: "php7-install.yml"
#        when: php_install|default(False)|bool
